### ISSUE TITLE
关于Experimental Setups，有问题请教您

### ISSUE THREAD

**Issue by zhengguanyu** [Hi-archers/StableKE#1]
非常感谢您的work，很有启发！我对于全文有一点疑惑，盼望您指教！

在Experimental Setups中并未找到您用于评估各个知识编辑方法的LLM，我又翻阅了文中其他部分，也没有找到明确标识之处。请问您在实验中编辑的LLM是什么？谢谢您！

祝好！

**Comment by Hi-archers** [comment]
感谢您的关心，我论文中使用的均为Vicuna 1.1模型
---- 回复的原邮件 ----
发件人 Steven ***@***.***> 日期 2024年12月04日 22:54 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [Hi-archers/StableKE] 关于Experimental Setups，有问题请教您 (Issue #1) 
非常感谢您的work，很有启发！我对于全文有一点疑惑，盼望您指教！
在Experimental Setups中并未找到您用于评估各个知识编辑方法的LLM，我又翻阅了文中其他部分，也没有找到明确标识之处。请问您在实验中编辑的LLM是什么？谢谢您！
祝好！

**Comment by zhengguanyu** [comment]
好迅速，感谢您的回复！我还有两个疑惑打扰您，不好意思...

①我对知识编辑不算熟悉，请问StableKE中的SPE和CDE均使用ChatGPT生成数据，用于编辑Vicuna 1.1。这样和baseline做对比时候，是否会损失对比的公平性？

②您的Table1中的'''StableKE+LoRA'''是采用了Lora做微调，那么'''StableKE'''是采用了全参数微调吗？

祝好！

**Comment by Hi-archers** [comment]
1. 我们更多的强调的是使用复述增加多样性就好了，增强模型不太关键，我们之前有做过实验使用Vicuna模型作为增强模型，表现有几个点的下降，但是影响不会太大，我明天给您找一下结果给您。
2. 是的。
---- 回复的原邮件 ----
发件人 Steven ***@***.***> 日期 2024年12月04日 23:34 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [Hi-archers/StableKE] 关于Experimental Setups，有问题请教您 (Issue #1) 
好迅速，感谢您的回复！我还有两个疑惑打扰您，不好意思...
①我对知识编辑不算熟悉，请问StableKE中的SPE和CDE均使用ChatGPT生成数据，用于编辑Vicuna 1.1。这样和baseline做对比时候，是否会损失对比的公平性？
②您的Table1中的'''StableKE+LoRA'''是采用了Lora做微调，那么'''StableKE'''是采用了全参数微调吗？
祝好！

**Comment by zhengguanyu** [comment]
非常感谢您的回复！ 祝好！
